fix: disable constraint on PDUSessionResourceReleaseTransfer
We have the following error:

[fleroy:~/github/FredericLeroy/libngap] develop(+1521/-1378)* 6h5m2s 2 ± make
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/ProtocolExtensionField.o -c src/ProtocolExtensionField.c
src/ProtocolExtensionField.c:25223:6: error: ‘asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’ undeclared here (not in a function); did you mean ‘memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368’?
   { &asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6, &asn_PER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6,  memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368
src/ProtocolExtensionField.c:25223:97: error: ‘asn_PER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’ undeclared here (not in a function); did you mean ‘asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’?
 n_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6, &asn_PER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6,  memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                 asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6
Makefile:27: recipe for target 'src/ProtocolExtensionField.o' failed
make: *** [src/ProtocolExtensionField.o] Error 1

So functions ‘asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’ and ‘asn_PER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’
are not generated by asn1c.

What are these functions ?

Looking at the code src/ProtocolExtensionField.c:25223 we have

static asn_TYPE_member_t asn_MBR_extensionValue_368[] = {
    { ATF_NOFLAGS, 0, offsetof(struct PDUSessionResourceItemCxtRelCpl_ExtIEs__extensionValue, choice.OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer_),
        (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
        0,
        &asn_DEF_OCTET_STRING,
        0,
        { &asn_OER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6, &asn_PER_memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6,  memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },
        0, 0, /* No default value */
        "OCTET STRING (CONTAINING PDUSessionResourceReleaseResponseTransfer)"
        },
};

so looking for asn_TYPE_member_t definitions :

typedef struct asn_TYPE_member_s {
    enum asn_TYPE_flags_e flags; /* Element's presentation flags */
    unsigned optional;      /* Following optional members, including current */
    unsigned memb_offset;   /* Offset of the element */
    ber_tlv_tag_t tag;      /* Outmost (most immediate) tag */
    int tag_mode;           /* IMPLICIT/no/EXPLICIT tag at current level */
    asn_TYPE_descriptor_t *type;            /* Member type descriptor */
    asn_type_selector_f *type_selector;     /* IoS runtime type selector */
    asn_encoding_constraints_t encoding_constraints;
    int (*default_value_cmp)(const void *sptr); /* Compare DEFAULT <value> */
    int (*default_value_set)(void **sptr);      /* Set DEFAULT <value> */
    const char *name; /* ASN.1 identifier of the element */
} asn_TYPE_member_t;

We can deduce that the missing functions are in a asn_encoding_constraints_t type.
Looking for this type:

/*
   * A constraints tuple specifying both the OER and PER constraints.
   */
  typedef struct asn_encoding_constraints_s {
      const struct asn_oer_constraints_s *oer_constraints;
      const struct asn_per_constraints_s *per_constraints;
      asn_constr_check_f *general_constraints;
  } asn_encoding

So we can guess that missing functions are only for checking constraints of type at runtime for oer and per formats.

If we disable these check:

      { 0, 0,  memb_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },

 The source code compile successfully !

We have lost constraint functionality for oer and per.